### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by seega** [wotmshuaisi/wolfmonitor#1]
Hello, how to fix this problem?
> root@v41527:~/wolfmonitor# python3 main.py
> Traceback (most recent call last):
>   File "main.py", line 5, in <module>
>     from lib.net import get_remote_detail
>   File "/root/wolfmonitor/lib/net.py", line 5, in <module>
>     from lib.geoip import GeoIPClient
>   File "/root/wolfmonitor/lib/geoip.py", line 4, in <module>
>     class GeoIPClient:
>   File "/root/wolfmonitor/lib/geoip.py", line 5, in GeoIPClient
>     R = geoip2.database.Reader("data/GeoLite2-City.mmdb")
>   File "/usr/local/lib/python3.6/dist-packages/geoip2/database.py", line 82, in __init__
>     self._db_reader = maxminddb.open_database(filename, mode)
>   File "/usr/local/lib/python3.6/dist-packages/maxminddb/__init__.py", line 41, in open_database
>     return maxminddb.reader.Reader(database, mode)
>   File "/usr/local/lib/python3.6/dist-packages/maxminddb/reader.py", line 52, in __init__
>     with open(database, 'rb') as db_file:
> FileNotFoundError: [Errno 2] No such file or directory: 'data/GeoLite2-City.mmdb

**Comment by wotmshuaisi** [comment]
hi
download the GeoIP database from the official website [GeoLite2-City.tar.gz](http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz), decompress it, and put it on this program's `data` directory

**Comment by seega** [comment]
@wotmshuaisi Thank you, launched. Please tell the full path to the map, at the ip:9999/ - `404: Not Found`, at the ip:9999/ws `Can "Upgrade" only to "WebSocket".`

**Comment by wotmshuaisi** [comment]
@seega  the `9999` port is from WebSocket server.

before you open the monitor map, you need start `Docker Image` which is the image you built it on the WolfMonitor root path.

after that, try open the `http://localhost/` or `http://[docker image url]/`, if it still not working, leave a message again

**Comment by seega** [comment]
@wotmshuaisi thank you, work with `docker run -d -p 80:80 xxx` 
but now, by running `main.py`:
> WARNING:tornado.access:403 GET /ws (MY_IP) 2.23ms
> WARNING:tornado.access:403 GET /ws (MY_IP) 2.72ms
> WARNING:tornado.access:403 GET /ws (MY_IP) 1.13ms
> WARNING:tornado.access:403 GET /ws (MY_IP) 0.98ms

connection are not displayed on the map
upd: i change ip to real in `config/config.py` no erros, but map clear
upd2: try fresh install on new server, works good now :)

**Comment by seega** [comment]
@wotmshuaisi How do I monitor the port that is running in the Docker app?

**Comment by wotmshuaisi** [comment]
@seega I wrote a `check_origins` function, that will deny the unknown origins. make sure only the same domain or IP can access this websocket server

**Comment by wotmshuaisi** [comment]
@seega monitor the port on running docker, you can mapping the container's port to the real host

**Comment by seega** [comment]
@wotmshuaisi I have an application running in the docker, connections to it go without problems, but as I understand it they can not be intercepted by the `main.py`. if on the same server I run a similar application on the python, the monitor perfectly shows all the connections. For example, if you enter port 80, the monitor does not work.

**Comment by wotmshuaisi** [comment]
@seega make sure this program got permission to access 80 port, then use the command `netstat -tlnpa | grep [port]` to show the container's port, if it already mapping success and `wolfmonitor` got permission to access 80 port, it should work perfectly

**Comment by seega** [comment]
@wotmshuaisi I have the following situation, for example port 22 normally monitors, all ports that are not monitored through the docker, like 80 from the project and my 443

**Comment by wotmshuaisi** [comment]
@seega forgive me, i'm not good at english, did you run this program on 127.0.0.1 that local address?, this program works well on my server, here's my config, change `html/ipviking.js` to your server address  on line 68,  secondly change `config/config.py` `SERVER_IP` to your server address, that server address must can be access on the internet
